[[redirects]]
  from = "/nyhome.html"
  to = "/ny"

[[redirects]]
  from = "/nyevents.html"
  to = "/ny/events"

[[redirects]]
  from = "/nylockerroom.html"
  to = "/ny/locker"

[[redirects]]
  from = "/nyleagues.html"
  to = "/ny/leagues"

[[redirects]]
  from = "/nypress.html"
  to = "/ny"

[[redirects]]
  from = "/nycontact.html"
  to = "/ny/contact"

[[redirects]]
  from = "/lahome.html"
  to = "/la"

[[redirects]]
  from = "/laevents.html"
  to = "/la/events"

[[redirects]]
  from = "/laleagues.html"
  to = "/la/leagues"

[[redirects]]
  from = "/lapress.html"
  to = "/la"

[[redirects]]
  from = "/lacontact.html"
  to = "/la/contact"
