backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "la-weekly-events"
    label: "LA Weekly Events"
    description: "Weekly Events"
    create: true
    folder: "_data/weekly/la"
    fields:
      - { label: "Day of Week", name: "day", widget: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "event-link", widget: "string", required: false }
  - name: "menus"
    label: "Menus"
    description: "Sectioned menus"
    extension: "json"
    files:
      - label: "LA Menu"
        name: "la-menu"
        file: "_data/la-menu.json"
        fields:
          - label: "Sections" 
            name: "sections"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "description", widget: "string", required: false }
  - name: "ftl-menu"
    label: "FTL Menu"
    description: "All food items will appear grouped by section."
    create: true
    folder: "_data/menu/ftl"
    fields:
      - { label: "Menu Section", name: "section", widget: "string" }
      - name: "menu-item"
        label: "Menu Item"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
  - name: "ny-posters"
    label: "NY Posters"
    label_singular: "NY Poster"
    description: "These posters appear in the home page"
    create: true
    folder: "_data/posters/ny"
    fields:
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
  - name: "la-posters"
    label: "LA Posters"
    label_singular: "LA Poster"
    description: "These posters appear in the home page"
    create: true
    folder: "_data/posters/la"
    fields:
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
  - name: "ftl-posters"
    label: "FTL Posters"
    label_singular: "FTL Poster"
    description: "These posters appear in the home page"
    create: true
    folder: "_data/posters/ftl"
    fields:
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
