backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "ny-posters"
    label: "NY Posters"
    label_singular: "NY Poster"
    description: "These posters appear in the New York Home Page"
    folder: "_posters/ny"
    create: true
    fields:
      - { label: "Image URL", name: "url", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
