backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "ny-posters"
    label: "Posters"
    label_singular: "Poster"
    format: "json"
    extension: "json"
    description: "These posters appear in home pages"
    create: true
    files:
      - label: "NY Posters"
        name: "ny-posters"
        file: "_data/posters/ny.json"
        fields:
          - { label: "Image URL", name: "url", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
      - label: "FTL Posters"
        name: "ftl-posters"
        file: "_data/posters/ftl.json"
        fields:
          - { label: "Image URL", name: "url", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
      - label: "LA Posters"
        name: "la-posters"
        file: "_data/posters/la.json"
        fields:
          - { label: "Image URL", name: "url", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
